org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Djdk.net.unixdomain.tmpdir=C:\\Temp
# AF_UNIX tmpdir fix for this box (short 8.3 path breaks JDK NIO self-pipe).
org.gradle.parallel=false

mod_version=0.1.0
maven_group=dev.s1mp1e
archives_base_name=s1mp1e-1.16.5

# MC 1.16.5 Fabric — last Java-8 version, last with full fixed-function GL.
minecraft_version=1.16.5
yarn_mappings=1.16.5+build.10
loader_version=0.15.11
fabric_version=0.42.0+1.16
org.gradle.java.installations.paths=C:/Temp/jdk8dl/jdk8u502-b07
